import Foundation

// Phase A6 — autofix checklist-PR mode (no file writes).
public enum ChecklistPR {
    public static func markdown(from report: AuditReport) -> String {
        var lines = [
            "## Duo harness checklist",
            "",
            "_Generated by `duo-harness autofix --checklist`. Mechanical autofix only rewrites `UIScreen.main.scale` → `traitCollection.displayScale`._",
            "",
        ]
        if report.findings.isEmpty {
            lines.append("- [x] No findings")
            return lines.joined(separator: "\n") + "\n"
        }
        for finding in report.findings {
            let mechanical = finding.id == "R1.UIScreenMain" ? " (mechanical autofix eligible for `.scale`)" : ""
            lines.append(
                "- [ ] `\(finding.id)` `\(finding.file):\(finding.line)` — \(finding.message)\(mechanical)"
            )
            lines.append("  - \(finding.suggestion)")
        }
        return lines.joined(separator: "\n") + "\n"
    }
}
